// Fallback listings shown when Supabase isn't connected yet.
// Once Supabase env vars are set, the site automatically switches to real database data —
// nothing here needs to change.
import { Listing } from './types'

export const mockListings: Listing[] = [
  {
    id: 'mock-zephyrus-g15',
    title: 'ROG Zephyrus G15',
    category: 'laptop',
    brand: 'Asus',
    price: 240000,
    currency: 'PKR',
    price_firm: false,
    condition: 'Excellent',
    location: 'Islamabad/Rawalpindi',
    status: 'available',
    specs: ['Ryzen 9 5900HS', 'RTX 3070 8GB', '16GB DDR4', '1TB NVMe SSD', '2K 165Hz'],
    description: null,
    photos: [],
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-omen-16',
    title: 'Omen 16',
    category: 'laptop',
    brand: 'HP',
    price: 265000,
    currency: 'PKR',
    price_firm: false,
    condition: '10/10 Like New',
    location: 'Islamabad/Rawalpindi',
    status: 'available',
    specs: ['i7-13620H', 'RTX 4060 8GB', '16GB DDR5', '1TB Gen4 NVMe', '144Hz IPS'],
    description: null,
    photos: [],
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-nitro-5',
    title: 'Nitro 5',
    category: 'laptop',
    brand: 'Acer',
    price: 255000,
    currency: 'PKR',
    price_firm: false,
    condition: 'Excellent',
    location: 'Islamabad/Rawalpindi',
    status: 'available',
    specs: ['i9-12900H', 'RTX 4060 8GB', '16GB RAM', '1TB NVMe', 'FHD 165Hz'],
    description: null,
    photos: [],
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-ps5-slim',
    title: 'PS5 Slim — Disc Edition',
    category: 'console',
    brand: 'Sony',
    price: 200000,
    currency: 'PKR',
    price_firm: true,
    condition: '9.5/10 Excellent',
    location: 'Islamabad/Rawalpindi',
    status: 'available',
    specs: ['Model CFI-2015', 'High-speed SSD', '1x DualSense incl.', 'Box not incl.'],
    description: null,
    photos: [],
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
